name: spaceborne
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - matplotlib
  - numpy
  - scipy
  - pandas
  - tqdm
  - pip
  - pyyaml
  - astropy
  - ipykernel
  - ipywidgets
  - joblib
  - numba
  - pyyaml
  - pip:
    - chainconsumer 
    - getdist
    - type_enforced
    - array_to_latex
    - pynverse
    #- classy
    - camb
    - ray