name: spaceborne
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - matplotlib
  - numpy
  - scipy
  - pandas
  - tqdm
  - pip
  - pyyaml
  - astropy
  - ipykernel
  - ipywidgets
  - joblib
  - numba
  - pyyaml
  - camb
  - cmake
  - pip:
    - chainconsumer 
    - getdist
    - type_enforced
    - array_to_latex
    - pynverse
    #- classy
    - ray
    - PyQt5
    - PySide2
    #- pyccl

# To install the master version of pyccl:
# $ conda activate spaceborne
# $ git clone https://github.com/LSSTDESC/CCL.git
# $ cd CCL    
# $ pip install .
# $ cd .. 
# $ rm -r CCL
