name: spaceborne-pip
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11
  - matplotlib
  - numpy
  - scipy
  - pandas
  - tqdm
  - pip
  - pyyaml
  - astropy
  - joblib
  - numba
  - camb
  - cmake
  - gcc
  - pyqt
  - ipympl
  - swig
  - cfitsio
  # - pynverse
  - fast-pt
  - git
  - pip:
    - pymaster
    - cython
    - getdist
    - fast-pt
    - git+https://github.com/davidesciotti/CCL.git@master