# should I do this? maybe a function in the main should take care of creating this
# file, since it changes based on the number of bins or other settings

OmegaM: 0.268578108
OmegaDE: 0.68140775651
OmegaB: 0.05001413
wz: -1.0
wa: 0.0
h: 67.37
ns: 0.966
sigma8:
logT_AGN: 7.75
Aia: 0.16
etaIA: 1.66
#beta_IA: 0.0  # not varied in the analysis!

# shear bias
# dzWL
# galaxy bias
# magnification bias
# dzGC




